version: '3'
services:
  app:
    container_name: "app"
    build: 
      context: .
      dockerfile: build/dev/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    environment:
      GO_WORK_DIR: "/app"